name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: maven


    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1


    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2


    - name: Check versions
      run: |
        java -version
        google-chrome --version
        chromedriver --version


    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libglib2.0-0 \
          libnss3 \
          libxss1 \
          libasound2t64 \
          libxtst6 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libgbm1


    - name: Run Selenium Tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        mvn -B clean test -Dsurefire.useFile=false
